### ISSUE TITLE
Evaluation sampling interval 

### ISSUE THREAD

**Issue by xcharxlie** [Embracing/GFPose#3]
Did you use 640 as the sampling interval in evaluation or you evaluated on the whole test dataset?

**Comment by Embracing** [comment]
I use 640 as the sampling interval to save the evaluation time. I have also tried evaluating on the whole testset. This generally gives similar or even slightly better performance despite much longer evaluation time.

**Comment by xcharxlie** [comment]
And most of the results listed in the big table are probabilistic right, unless the ones are stated explicitly.

**Comment by Embracing** [comment]
In my experience, there is very little variance in the results of each evaluation. The results reported in the paper can be reproduced using the scripts and checkpoints provided in this repo.

**Comment by xcharxlie** [comment]
Thank you so much! I'm also looking forward to the 3dhp part of code for result comparison.
