### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by Sujith93** [Embracing/GFPose#4]
Hi, Thanks for the GitHub repo, I'm trying to learn by execuitng.
When I ran 
python -m run.visualize --num-human 1 --num-hypo 80 --vis-gt
or
python -m run.visualize --num-human 1 --num-hypo 40 --vis-gt

In the UI, I tried to select 3d.npz (https://github.com/Embracing/3DPoseViewer/blob/main/examples/seq1/3d.npz)
I'm getting the below error
gt3d: (11, 7, 14, 3)
pred3d: (11, 7, 14, 3)
camera: (11, 5, 5, 3)
map_center: (3,)
Traceback (most recent call last):
  File "/Users/Documents/GFPose/lib/utils/ui/window.py", line 385, in openfile
    self.update_3d()
  File "/Users/Documents/GFPose/lib/utils/ui/window.py", line 489, in update_3d
    pred_line_ends[:, 1] += self.interval_for_plot * (human_idx_this_frame // self.args.vis_num_perline)
IndexError: index 1 is out of bounds for axis 1 with size 1

**Comment by Embracing** [comment]
The example data (https://github.com/Embracing/3DPoseViewer/blob/main/examples/seq1/3d.npz) contain multi-person multi-camera sequences. It should be loaded with the viewer in the [3DPoseViewer repo](https://github.com/Embracing/3DPoseViewer#quickstart). The viewer in this GFPose repo is a modified version.

To visualize the GFPose generated results, please follow the instructions [here](https://github.com/Embracing/GFPose#task1---3d-pose-estimation). Download a pretrained model, run inference code & save results, then visualize with:
python -m run.visualize --num-human 1 --num-hypo 80 --vis-gt
