### ISSUE TITLE
Multi Person

### ISSUE THREAD

**Issue by gpastal24** [Embracing/GFPose#6]
Could this method be extended for multi person 3D HPE ?

**Comment by Embracing** [comment]
Sure. A naive  extension would treat multi-person as multiple single persons and solve them using GFPose repeatedly. But better designs should model interactions between multiple people and train GFPose on a multi-person dataset.

**Comment by gpastal24** [comment]
Hello thanks for your reply, I was mostly thinking about whether it would be possible to train a variant that outputs lets say N 3D poses directly from N 2D poses or better yet directly from a  heatmap representation. 

I suppose it is doable.

**Comment by Embracing** [comment]
Yeah. I agree with you. It is doable and might be worth a try.
